---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integrationprocesscontrolnumbers
  description: Microservicios para la pantalla Cifras Control Históricas de DO IMSS/Microservicios para la gestión de los indicadores configurados por cuenta individual.
  tags:
    - microservice
    - reporting
  links:
    - url: https://github.com/JCAL0199/Integrationprocesscontrolnumbers
      title: Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    endpoints/dev: https://api.dev.company1.mx/company/1/nci-bdnsardintegrationprocesscontrolnumbers
    endpoints/qa: https://api.qa.company1.mx/company/1/nci-bdnsardintegrationprocesscontrolnumbers
    endpoints/prod: https://api.company1.mx/company/1/nci-bdnsardintegrationprocesscontrolnumbers
spec:
  type: service
  owner: group:default/juan-manuel-perez
  lifecycle: production
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  description: Dispersión Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/service-flask
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  description: Dispersión Ordinaria IMSS/Carga Archivo -Edición
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  description: Dispersión Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
